name: bash workflow controller
on:
  push:
    branches:
      - "main"
      - "bash/release/**"
jobs:
  bash-controller-executor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out sources
        uses: actions/checkout@v6
      - name: locate on directory
        run: cd bash
      - name: running bash
        run: bash ./hello-world.sh
