name: Context practice
run-name: Practice context on pipeline
on: [push]
jobs:
  prod-check:
    name: Context practice variables
    runs-on: ubuntu-slim
    steps:
      - run: |
          echo "Github ref $GITHUB_REF"

      - env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        run: |
          echo "Github json $CONTEXT_GITHUB"

      - env:
          CONTEXT_VARS: ${{ toJSON(vars) }}
        run: |
          echo "Github vars $CONTEXT_VARS"

      - env:
          CONTEXT_JOB: ${{ toJSON(job) }}
        run: |
          echo "Github job $CONTEXT_JOB"

      - env:
          CONTEXT_STEPS: ${{ toJSON(steps) }}
        run: |
          echo "Github steps $CONTEXT_STEPS"

      - env:
          CONTEXT_RUNNER: ${{ toJSON(runner) }}
        run: |
          echo "Github runner $CONTEXT_RUNNER"
