name: Expression test
run-name: Expression evaluation workflow
on:
  workflow_dispatch:
    inputs:
      age:
        description: age
        required: true
        default: 18
        type: integer
      name:
        description: name
        default: default-name
        required: true
        type: string
jobs:
  evaluate-adult-age:
    if: ${{ inputs.age >= 18 }}
    runs-on: ubuntu-slim
    steps:
      - name: Evaluating adult age
        run: echo "is an adult"

  greet-regular-user:
    if: ${{ !contains(inputs.name,"admin") }}
    runs-on: ubuntu-slim
    steps:
      - name: Greeting users
        env:
          USERNAME: ${{ inputs.name }}
        run: |
          echo "Hello user $USERNAME"

  greet-for-admin:
    if: ${{ contains(inputs.name,"admin") }}
    runs-on: ubuntu-slim
    steps:
      - name: Greeting admin
        run: echo "hello admin"

  evalutate-teenage-age:
    if: ${{ inputs.age < 18 }}
    runs-on: ubuntu-slim
    steps:
      - name: Evaluating teenage age
        run: echo "is an teenager"
