name: Github comment request on pr
on:
  pull_request_review:
    types: [edited, dismissed]
jobs:
  commented:
    runs-on: ubuntu-latest
    steps:
      - name: commenting pr
        run: echo "MR commented"
